### PR TITLE
:bug: :recycle: removed min restriction to masks

### LINKED ISSUE #3719: [BUG] - Mask input values cannot be negative
### Bug Checklist

- [x] I have searched for existing issues to see if this has already been reported
- [x] The issue occurs while all Modules are disabled

### What Happened?

Mask input values cannot be negative

### What Did You Expect to Happen?

they should

### Steps to Reproduce

add -1

### What core and system version are you reporting this for?

v13

### What browser are you using?

FoundryVTT Desktop App

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by patrickmohrmann**
the min: 0 data model restriction was wrong for most fields

### CODE REVIEW

File: module/data/item/mask.mjs [hunk 1]
```diff
@@ -66,34 +66,38 @@ export default class MaskData extends ItemDataModel.mixin(
...
           nullable: true,
           integer:  true,
         } ),
         climb: new fields.NumberField( {
           required: true,
+          initial:  0,
           nullable: true,
           integer:  true,
         } )
       } ),
```
Comment (qrizzl) [inline module/data/item/mask.mjs:92]: If these are initially 0 and are expected to be a number, then they shouldn't be `nullable`, so I'd remove these (if they are `false` by default, otherwise write it down explicitly)

**Review by qrizzl — CHANGES_REQUESTED** [review]

**Review by qrizzl — APPROVED** [review]
